source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mafeng-Bryant/Specs.git'
source 'git@github.com:pinterest/ios-pdk.git'
use_frameworks!

platform :ios, '8.0'

target 'MShareKit_Example' do
  pod 'MShareKit', :path => '../'

  target 'MShareKit_Tests' do
    inherit! :search_paths

    
  end
end
